if(NOT BUFF_PANEL_CONFIG MATCHES "^(Release|RelWithDebInfo|MinSizeRel)$")
    message(FATAL_ERROR "dist requires a Release, RelWithDebInfo, or MinSizeRel build; Debug binaries are not published.")
endif()
foreach(name IN ITEMS d2rl-buff-panel.dll d2rl-buff-panel.mpq)
    if(NOT EXISTS "${BUFF_PANEL_PLUGIN_DIR}/${name}" OR IS_DIRECTORY "${BUFF_PANEL_PLUGIN_DIR}/${name}")
        message(FATAL_ERROR "Missing shipping file: ${BUFF_PANEL_PLUGIN_DIR}/${name}")
    endif()
endforeach()
file(READ "${BUFF_PANEL_PLUGIN_DIR}/d2rl-buff-panel.mpq" signature LIMIT 4 HEX)
if(NOT signature STREQUAL "4d50511a")
    message(FATAL_ERROR "Companion is not a packed MPQ archive.")
endif()
file(MAKE_DIRECTORY "${BUFF_PANEL_DIST_DIR}/d2rloader/plugins")
file(COPY_FILE "${BUFF_PANEL_PLUGIN_DIR}/d2rl-buff-panel.dll" "${BUFF_PANEL_DIST_DIR}/d2rloader/plugins/d2rl-buff-panel.dll" ONLY_IF_DIFFERENT)
file(COPY_FILE "${BUFF_PANEL_PLUGIN_DIR}/d2rl-buff-panel.mpq" "${BUFF_PANEL_DIST_DIR}/d2rloader/plugins/d2rl-buff-panel.mpq" ONLY_IF_DIFFERENT)
file(COPY_FILE "${BUFF_PANEL_SOURCE_DIR}/LICENSE" "${BUFF_PANEL_DIST_DIR}/LICENSE")
file(COPY_FILE "${BUFF_PANEL_SOURCE_DIR}/INSTALL.md" "${BUFF_PANEL_DIST_DIR}/INSTALL.md")
file(COPY_FILE "${BUFF_PANEL_SDK_LICENSE_FILE}" "${BUFF_PANEL_DIST_DIR}/PluginSDK-LICENSE")
file(SHA256 "${BUFF_PANEL_DIST_DIR}/d2rloader/plugins/d2rl-buff-panel.dll" dll_sha)
file(SHA256 "${BUFF_PANEL_DIST_DIR}/d2rloader/plugins/d2rl-buff-panel.mpq" mpq_sha)
file(WRITE "${BUFF_PANEL_DIST_DIR}/SHA256SUMS.txt" "${dll_sha}  d2rloader/plugins/d2rl-buff-panel.dll\n${mpq_sha}  d2rloader/plugins/d2rl-buff-panel.mpq\n")
